---
build:
  dependencies:
    before:
    - "pecl install mongodb"
    - "pecl install redis"
    - "cp .env.travis .env"
    - "composer update"
    - "php artisan key:generate"
  environment:
    mongodb: "4.0"
    php:
      version: 7.2
  tests:
    override:
    - php-scrutinizer-run
    -
      command: phpcs-run
      use_website_config: true
    - command: "vendor/bin/phpunit --coverage-clover=coverage.clover"
    - command: "wget https://scrutinizer-ci.com/ocular.phar"
    - command: "php ocular.phar code-coverage:upload --format=php-clover coverage.clover"
checks:
  php:
    code_rating: true
    duplication: true
    fix_doc_comments: true
    fix_identation_4spaces: true
    fix_line_ending: true
    fix_linefeed: true
    fix_php_opening_tag: true
    fix_use_statements:
      order_alphabetically: true
      preserve_blanklines: true
      preserve_multiple: false
      remove_unused: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
filter:
  excluded_paths:
  - tests/*
tools:
  external_code_coverage:
    timeout: 600
