language: php

dist: trusty
sudo: false

services:
- redis-server
- mongodb

addons:
  hosts:
  - larapi.test
  - api.larapi.test

env:
  global:
  - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
      
cache:
  directories:
    - $HOME/.composer/cache

before_install:
- echo '' > ./storage/logs/laravel.log
- echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
- cp .env.travis .env
- echo PUSHER_APP_SECRET=$PUSHER_APP_SECRET >> .env
- echo AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET >> .env
- echo AUTH0_TEST_USER_NAME=$AUTH0_TEST_USER_NAME >> .env
- echo AUTH0_TEST_USER_PASS=$AUTH0_TEST_USER_PASS >> .env
- composer update
- php artisan key:generate
- php artisan bootstrap:cache
- php artisan env:display
- composer update

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_failure:
- echo --------------- Begin > Laravel.log ---------------
- cat storage/logs/laravel.log
- echo --------------- End   > Laravel.log ---------------
