language: php

php:
- '7.2'

dist: trusty
sudo: false

services:
- redis-server
- mongodb

addons:
  hosts:
  - larapi.test
  - api.larapi.test

env:
  global:
  - setup=stable

matrix:
  fast_finish: true
  include:
  - php: 7.2
    env: setup=normal

before_install:
- echo '' > ./storage/logs/laravel.log
- echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- travis_retry composer self-update

install:
- if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --prefer-stable --no-interaction --no-suggest; fi
- if [[ $setup = 'normal' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi

before_script:
- cp .env.travis .env
- echo .env >> PUSHER_APP_SECRET=$PUSHER_APP_SECRET
- echo .env >> AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
- echo .env >> AUTH0_TEST_USER_NAME=$AUTH0_TEST_USER_NAME
- echo .env >> AUTH0_TEST_USER_PASS=$AUTH0_TEST_USER_PASS
- echo .env >> RANDOMVARIABLE=blablabla
- composer update
- php artisan key:generate
- php artisan bootstrap:cache
- php artisan route:cache
- php artisan config:cache
- php artisan env:display

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_failure:
- echo --------------- Begin > Laravel.log ---------------
- cat storage/logs/laravel.log
- echo --------------- End   > Laravel.log ---------------
